/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIStatusAppVersion model module.
 * @module model/APIStatusAppVersion
 * @version 3.5
 */
class APIStatusAppVersion {
    /**
     * Constructs a new <code>APIStatusAppVersion</code>.
     * @alias module:model/APIStatusAppVersion
     * @param minAppVersion {Number} Internal use - Minimum application version required to correctly connect and process data.
     * @param latestAppVersion {Number} Internal use - Latest application version available.
     */
    constructor(minAppVersion, latestAppVersion) { 
        
        APIStatusAppVersion.initialize(this, minAppVersion, latestAppVersion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, minAppVersion, latestAppVersion) { 
        obj['min_app_version'] = minAppVersion;
        obj['latest_app_version'] = latestAppVersion;
    }

    /**
     * Constructs a <code>APIStatusAppVersion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIStatusAppVersion} obj Optional instance to populate.
     * @return {module:model/APIStatusAppVersion} The populated <code>APIStatusAppVersion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIStatusAppVersion();

            if (data.hasOwnProperty('min_app_version')) {
                obj['min_app_version'] = ApiClient.convertToType(data['min_app_version'], 'Number');
            }
            if (data.hasOwnProperty('latest_app_version')) {
                obj['latest_app_version'] = ApiClient.convertToType(data['latest_app_version'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Internal use - Minimum application version required to correctly connect and process data.
 * @member {Number} min_app_version
 */
APIStatusAppVersion.prototype['min_app_version'] = undefined;

/**
 * Internal use - Latest application version available.
 * @member {Number} latest_app_version
 */
APIStatusAppVersion.prototype['latest_app_version'] = undefined;






export default APIStatusAppVersion;

