/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DistrictRankingEventPoints'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DistrictRankingEventPoints'));
  } else {
    // Browser globals (root is window)
    if (!root.TbaApiV3client) {
      root.TbaApiV3client = {};
    }
    root.TbaApiV3client.DistrictRanking = factory(root.TbaApiV3client.ApiClient, root.TbaApiV3client.DistrictRankingEventPoints);
  }
}(this, function(ApiClient, DistrictRankingEventPoints) {
  'use strict';




  /**
   * The DistrictRanking model module.
   * @module model/DistrictRanking
   * @version 3.03.1
   */

  /**
   * Constructs a new <code>DistrictRanking</code>.
   * Rank of a team in a district.
   * @alias module:model/DistrictRanking
   * @class
   * @param teamKey {String} TBA team key for the team.
   * @param rank {Number} Numerical rank of the team, 1 being top rank.
   * @param pointTotal {Number} Total district points for the team.
   */
  var exports = function(teamKey, rank, pointTotal) {
    var _this = this;

    _this['team_key'] = teamKey;
    _this['rank'] = rank;

    _this['point_total'] = pointTotal;

  };

  /**
   * Constructs a <code>DistrictRanking</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DistrictRanking} obj Optional instance to populate.
   * @return {module:model/DistrictRanking} The populated <code>DistrictRanking</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('team_key')) {
        obj['team_key'] = ApiClient.convertToType(data['team_key'], 'String');
      }
      if (data.hasOwnProperty('rank')) {
        obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
      }
      if (data.hasOwnProperty('rookie_bonus')) {
        obj['rookie_bonus'] = ApiClient.convertToType(data['rookie_bonus'], 'Number');
      }
      if (data.hasOwnProperty('point_total')) {
        obj['point_total'] = ApiClient.convertToType(data['point_total'], 'Number');
      }
      if (data.hasOwnProperty('event_points')) {
        obj['event_points'] = ApiClient.convertToType(data['event_points'], [DistrictRankingEventPoints]);
      }
    }
    return obj;
  }

  /**
   * TBA team key for the team.
   * @member {String} team_key
   */
  exports.prototype['team_key'] = undefined;
  /**
   * Numerical rank of the team, 1 being top rank.
   * @member {Number} rank
   */
  exports.prototype['rank'] = undefined;
  /**
   * Any points added to a team as a result of the rookie bonus.
   * @member {Number} rookie_bonus
   */
  exports.prototype['rookie_bonus'] = undefined;
  /**
   * Total district points for the team.
   * @member {Number} point_total
   */
  exports.prototype['point_total'] = undefined;
  /**
   * List of events that contributed to the point total for the team.
   * @member {Array.<module:model/DistrictRankingEventPoints>} event_points
   */
  exports.prototype['event_points'] = undefined;



  return exports;
}));


