/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WLTRecord from './WLTRecord';

/**
 * The EliminationAllianceStatus model module.
 * @module model/EliminationAllianceStatus
 * @version 3.5
 */
class EliminationAllianceStatus {
    /**
     * Constructs a new <code>EliminationAllianceStatus</code>.
     * @alias module:model/EliminationAllianceStatus
     */
    constructor() { 
        
        EliminationAllianceStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EliminationAllianceStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EliminationAllianceStatus} obj Optional instance to populate.
     * @return {module:model/EliminationAllianceStatus} The populated <code>EliminationAllianceStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EliminationAllianceStatus();

            if (data.hasOwnProperty('playoff_average')) {
                obj['playoff_average'] = ApiClient.convertToType(data['playoff_average'], 'Number');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('record')) {
                obj['record'] = WLTRecord.constructFromObject(data['record']);
            }
            if (data.hasOwnProperty('current_level_record')) {
                obj['current_level_record'] = WLTRecord.constructFromObject(data['current_level_record']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} playoff_average
 */
EliminationAllianceStatus.prototype['playoff_average'] = undefined;

/**
 * @member {String} level
 */
EliminationAllianceStatus.prototype['level'] = undefined;

/**
 * @member {module:model/WLTRecord} record
 */
EliminationAllianceStatus.prototype['record'] = undefined;

/**
 * @member {module:model/WLTRecord} current_level_record
 */
EliminationAllianceStatus.prototype['current_level_record'] = undefined;

/**
 * @member {String} status
 */
EliminationAllianceStatus.prototype['status'] = undefined;






export default EliminationAllianceStatus;

