/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventDistrictPointsPoints model module.
 * @module model/EventDistrictPointsPoints
 * @version 3.04.1
 */
class EventDistrictPointsPoints {
    /**
     * Constructs a new <code>EventDistrictPointsPoints</code>.
     * @alias module:model/EventDistrictPointsPoints
     * @param total {Number} Total points awarded at this event.
     * @param alliancePoints {Number} Points awarded for alliance selection
     * @param elimPoints {Number} Points awarded for elimination match performance.
     * @param awardPoints {Number} Points awarded for event awards.
     * @param qualPoints {Number} Points awarded for qualification match performance.
     */
    constructor(total, alliancePoints, elimPoints, awardPoints, qualPoints) { 
        
        EventDistrictPointsPoints.initialize(this, total, alliancePoints, elimPoints, awardPoints, qualPoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, alliancePoints, elimPoints, awardPoints, qualPoints) { 
        obj['total'] = total;
        obj['alliance_points'] = alliancePoints;
        obj['elim_points'] = elimPoints;
        obj['award_points'] = awardPoints;
        obj['qual_points'] = qualPoints;
    }

    /**
     * Constructs a <code>EventDistrictPointsPoints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventDistrictPointsPoints} obj Optional instance to populate.
     * @return {module:model/EventDistrictPointsPoints} The populated <code>EventDistrictPointsPoints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventDistrictPointsPoints();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('alliance_points')) {
                obj['alliance_points'] = ApiClient.convertToType(data['alliance_points'], 'Number');
            }
            if (data.hasOwnProperty('elim_points')) {
                obj['elim_points'] = ApiClient.convertToType(data['elim_points'], 'Number');
            }
            if (data.hasOwnProperty('award_points')) {
                obj['award_points'] = ApiClient.convertToType(data['award_points'], 'Number');
            }
            if (data.hasOwnProperty('qual_points')) {
                obj['qual_points'] = ApiClient.convertToType(data['qual_points'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Total points awarded at this event.
 * @member {Number} total
 */
EventDistrictPointsPoints.prototype['total'] = undefined;

/**
 * Points awarded for alliance selection
 * @member {Number} alliance_points
 */
EventDistrictPointsPoints.prototype['alliance_points'] = undefined;

/**
 * Points awarded for elimination match performance.
 * @member {Number} elim_points
 */
EventDistrictPointsPoints.prototype['elim_points'] = undefined;

/**
 * Points awarded for event awards.
 * @member {Number} award_points
 */
EventDistrictPointsPoints.prototype['award_points'] = undefined;

/**
 * Points awarded for qualification match performance.
 * @member {Number} qual_points
 */
EventDistrictPointsPoints.prototype['qual_points'] = undefined;






export default EventDistrictPointsPoints;

