/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TbaApiV3client) {
      root.TbaApiV3client = {};
    }
    root.TbaApiV3client.EventDistrictPointsTiebreakers = factory(root.TbaApiV3client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EventDistrictPointsTiebreakers model module.
   * @module model/EventDistrictPointsTiebreakers
   * @version 3.03.1
   */

  /**
   * Constructs a new <code>EventDistrictPointsTiebreakers</code>.
   * @alias module:model/EventDistrictPointsTiebreakers
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>EventDistrictPointsTiebreakers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventDistrictPointsTiebreakers} obj Optional instance to populate.
   * @return {module:model/EventDistrictPointsTiebreakers} The populated <code>EventDistrictPointsTiebreakers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('highest_qual_scores')) {
        obj['highest_qual_scores'] = ApiClient.convertToType(data['highest_qual_scores'], ['Number']);
      }
      if (data.hasOwnProperty('qual_wins')) {
        obj['qual_wins'] = ApiClient.convertToType(data['qual_wins'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Number>} highest_qual_scores
   */
  exports.prototype['highest_qual_scores'] = undefined;
  /**
   * @member {Number} qual_wins
   */
  exports.prototype['qual_wins'] = undefined;



  return exports;
}));


