/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TbaApiV3client) {
      root.TbaApiV3client = {};
    }
    root.TbaApiV3client.MatchScoreBreakdown2015Alliance = factory(root.TbaApiV3client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MatchScoreBreakdown2015Alliance model module.
   * @module model/MatchScoreBreakdown2015Alliance
   * @version 3.03.1
   */

  /**
   * Constructs a new <code>MatchScoreBreakdown2015Alliance</code>.
   * @alias module:model/MatchScoreBreakdown2015Alliance
   * @class
   */
  var exports = function() {
    var _this = this;

























  };

  /**
   * Constructs a <code>MatchScoreBreakdown2015Alliance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MatchScoreBreakdown2015Alliance} obj Optional instance to populate.
   * @return {module:model/MatchScoreBreakdown2015Alliance} The populated <code>MatchScoreBreakdown2015Alliance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('auto_points')) {
        obj['auto_points'] = ApiClient.convertToType(data['auto_points'], 'Number');
      }
      if (data.hasOwnProperty('teleop_points')) {
        obj['teleop_points'] = ApiClient.convertToType(data['teleop_points'], 'Number');
      }
      if (data.hasOwnProperty('container_points')) {
        obj['container_points'] = ApiClient.convertToType(data['container_points'], 'Number');
      }
      if (data.hasOwnProperty('tote_points')) {
        obj['tote_points'] = ApiClient.convertToType(data['tote_points'], 'Number');
      }
      if (data.hasOwnProperty('litter_points')) {
        obj['litter_points'] = ApiClient.convertToType(data['litter_points'], 'Number');
      }
      if (data.hasOwnProperty('foul_points')) {
        obj['foul_points'] = ApiClient.convertToType(data['foul_points'], 'Number');
      }
      if (data.hasOwnProperty('adjust_points')) {
        obj['adjust_points'] = ApiClient.convertToType(data['adjust_points'], 'Number');
      }
      if (data.hasOwnProperty('total_points')) {
        obj['total_points'] = ApiClient.convertToType(data['total_points'], 'Number');
      }
      if (data.hasOwnProperty('foul_count')) {
        obj['foul_count'] = ApiClient.convertToType(data['foul_count'], 'Number');
      }
      if (data.hasOwnProperty('tote_count_far')) {
        obj['tote_count_far'] = ApiClient.convertToType(data['tote_count_far'], 'Number');
      }
      if (data.hasOwnProperty('tote_count_near')) {
        obj['tote_count_near'] = ApiClient.convertToType(data['tote_count_near'], 'Number');
      }
      if (data.hasOwnProperty('tote_set')) {
        obj['tote_set'] = ApiClient.convertToType(data['tote_set'], 'Boolean');
      }
      if (data.hasOwnProperty('tote_stack')) {
        obj['tote_stack'] = ApiClient.convertToType(data['tote_stack'], 'Boolean');
      }
      if (data.hasOwnProperty('container_count_level1')) {
        obj['container_count_level1'] = ApiClient.convertToType(data['container_count_level1'], 'Number');
      }
      if (data.hasOwnProperty('container_count_level2')) {
        obj['container_count_level2'] = ApiClient.convertToType(data['container_count_level2'], 'Number');
      }
      if (data.hasOwnProperty('container_count_level3')) {
        obj['container_count_level3'] = ApiClient.convertToType(data['container_count_level3'], 'Number');
      }
      if (data.hasOwnProperty('container_count_level4')) {
        obj['container_count_level4'] = ApiClient.convertToType(data['container_count_level4'], 'Number');
      }
      if (data.hasOwnProperty('container_count_level5')) {
        obj['container_count_level5'] = ApiClient.convertToType(data['container_count_level5'], 'Number');
      }
      if (data.hasOwnProperty('container_count_level6')) {
        obj['container_count_level6'] = ApiClient.convertToType(data['container_count_level6'], 'Number');
      }
      if (data.hasOwnProperty('container_set')) {
        obj['container_set'] = ApiClient.convertToType(data['container_set'], 'Boolean');
      }
      if (data.hasOwnProperty('litter_count_container')) {
        obj['litter_count_container'] = ApiClient.convertToType(data['litter_count_container'], 'Number');
      }
      if (data.hasOwnProperty('litter_count_landfill')) {
        obj['litter_count_landfill'] = ApiClient.convertToType(data['litter_count_landfill'], 'Number');
      }
      if (data.hasOwnProperty('litter_count_unprocessed')) {
        obj['litter_count_unprocessed'] = ApiClient.convertToType(data['litter_count_unprocessed'], 'Number');
      }
      if (data.hasOwnProperty('robot_set')) {
        obj['robot_set'] = ApiClient.convertToType(data['robot_set'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} auto_points
   */
  exports.prototype['auto_points'] = undefined;
  /**
   * @member {Number} teleop_points
   */
  exports.prototype['teleop_points'] = undefined;
  /**
   * @member {Number} container_points
   */
  exports.prototype['container_points'] = undefined;
  /**
   * @member {Number} tote_points
   */
  exports.prototype['tote_points'] = undefined;
  /**
   * @member {Number} litter_points
   */
  exports.prototype['litter_points'] = undefined;
  /**
   * @member {Number} foul_points
   */
  exports.prototype['foul_points'] = undefined;
  /**
   * @member {Number} adjust_points
   */
  exports.prototype['adjust_points'] = undefined;
  /**
   * @member {Number} total_points
   */
  exports.prototype['total_points'] = undefined;
  /**
   * @member {Number} foul_count
   */
  exports.prototype['foul_count'] = undefined;
  /**
   * @member {Number} tote_count_far
   */
  exports.prototype['tote_count_far'] = undefined;
  /**
   * @member {Number} tote_count_near
   */
  exports.prototype['tote_count_near'] = undefined;
  /**
   * @member {Boolean} tote_set
   */
  exports.prototype['tote_set'] = undefined;
  /**
   * @member {Boolean} tote_stack
   */
  exports.prototype['tote_stack'] = undefined;
  /**
   * @member {Number} container_count_level1
   */
  exports.prototype['container_count_level1'] = undefined;
  /**
   * @member {Number} container_count_level2
   */
  exports.prototype['container_count_level2'] = undefined;
  /**
   * @member {Number} container_count_level3
   */
  exports.prototype['container_count_level3'] = undefined;
  /**
   * @member {Number} container_count_level4
   */
  exports.prototype['container_count_level4'] = undefined;
  /**
   * @member {Number} container_count_level5
   */
  exports.prototype['container_count_level5'] = undefined;
  /**
   * @member {Number} container_count_level6
   */
  exports.prototype['container_count_level6'] = undefined;
  /**
   * @member {Boolean} container_set
   */
  exports.prototype['container_set'] = undefined;
  /**
   * @member {Number} litter_count_container
   */
  exports.prototype['litter_count_container'] = undefined;
  /**
   * @member {Number} litter_count_landfill
   */
  exports.prototype['litter_count_landfill'] = undefined;
  /**
   * @member {Number} litter_count_unprocessed
   */
  exports.prototype['litter_count_unprocessed'] = undefined;
  /**
   * @member {Boolean} robot_set
   */
  exports.prototype['robot_set'] = undefined;



  return exports;
}));


