/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamEventStatusAllianceBackup model module.
 * @module model/TeamEventStatusAllianceBackup
 * @version 3.8.0
 */
class TeamEventStatusAllianceBackup {
    /**
     * Constructs a new <code>TeamEventStatusAllianceBackup</code>.
     * Backup status, may be null.
     * @alias module:model/TeamEventStatusAllianceBackup
     */
    constructor() { 
        
        TeamEventStatusAllianceBackup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamEventStatusAllianceBackup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamEventStatusAllianceBackup} obj Optional instance to populate.
     * @return {module:model/TeamEventStatusAllianceBackup} The populated <code>TeamEventStatusAllianceBackup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamEventStatusAllianceBackup();

            if (data.hasOwnProperty('out')) {
                obj['out'] = ApiClient.convertToType(data['out'], 'String');
            }
            if (data.hasOwnProperty('in')) {
                obj['in'] = ApiClient.convertToType(data['in'], 'String');
            }
        }
        return obj;
    }


}

/**
 * TBA key for the team replaced by the backup.
 * @member {String} out
 */
TeamEventStatusAllianceBackup.prototype['out'] = undefined;

/**
 * TBA key for the backup team called in.
 * @member {String} in
 */
TeamEventStatusAllianceBackup.prototype['in'] = undefined;






export default TeamEventStatusAllianceBackup;

