/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TeamEventStatusAlliance', 'model/TeamEventStatusPlayoff', 'model/TeamEventStatusRank'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TeamEventStatusAlliance'), require('./TeamEventStatusPlayoff'), require('./TeamEventStatusRank'));
  } else {
    // Browser globals (root is window)
    if (!root.TbaApiV3client) {
      root.TbaApiV3client = {};
    }
    root.TbaApiV3client.TeamEventStatus = factory(root.TbaApiV3client.ApiClient, root.TbaApiV3client.TeamEventStatusAlliance, root.TbaApiV3client.TeamEventStatusPlayoff, root.TbaApiV3client.TeamEventStatusRank);
  }
}(this, function(ApiClient, TeamEventStatusAlliance, TeamEventStatusPlayoff, TeamEventStatusRank) {
  'use strict';




  /**
   * The TeamEventStatus model module.
   * @module model/TeamEventStatus
   * @version 3.03.1
   */

  /**
   * Constructs a new <code>TeamEventStatus</code>.
   * @alias module:model/TeamEventStatus
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>TeamEventStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamEventStatus} obj Optional instance to populate.
   * @return {module:model/TeamEventStatus} The populated <code>TeamEventStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('qual')) {
        obj['qual'] = TeamEventStatusRank.constructFromObject(data['qual']);
      }
      if (data.hasOwnProperty('alliance')) {
        obj['alliance'] = TeamEventStatusAlliance.constructFromObject(data['alliance']);
      }
      if (data.hasOwnProperty('playoff')) {
        obj['playoff'] = TeamEventStatusPlayoff.constructFromObject(data['playoff']);
      }
      if (data.hasOwnProperty('alliance_status_str')) {
        obj['alliance_status_str'] = ApiClient.convertToType(data['alliance_status_str'], 'String');
      }
      if (data.hasOwnProperty('playoff_status_str')) {
        obj['playoff_status_str'] = ApiClient.convertToType(data['playoff_status_str'], 'String');
      }
      if (data.hasOwnProperty('overall_status_str')) {
        obj['overall_status_str'] = ApiClient.convertToType(data['overall_status_str'], 'String');
      }
      if (data.hasOwnProperty('next_match_key')) {
        obj['next_match_key'] = ApiClient.convertToType(data['next_match_key'], 'String');
      }
      if (data.hasOwnProperty('last_match_key')) {
        obj['last_match_key'] = ApiClient.convertToType(data['last_match_key'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/TeamEventStatusRank} qual
   */
  exports.prototype['qual'] = undefined;
  /**
   * @member {module:model/TeamEventStatusAlliance} alliance
   */
  exports.prototype['alliance'] = undefined;
  /**
   * @member {module:model/TeamEventStatusPlayoff} playoff
   */
  exports.prototype['playoff'] = undefined;
  /**
   * An HTML formatted string suitable for display to the user containing the team's alliance pick status.
   * @member {String} alliance_status_str
   */
  exports.prototype['alliance_status_str'] = undefined;
  /**
   * An HTML formatter string suitable for display to the user containing the team's playoff status.
   * @member {String} playoff_status_str
   */
  exports.prototype['playoff_status_str'] = undefined;
  /**
   * An HTML formatted string suitable for display to the user containing the team's overall status summary of the event.
   * @member {String} overall_status_str
   */
  exports.prototype['overall_status_str'] = undefined;
  /**
   * TBA match key for the next match the team is scheduled to play in at this event, or null.
   * @member {String} next_match_key
   */
  exports.prototype['next_match_key'] = undefined;
  /**
   * TBA match key for the last match the team played in at this event, or null.
   * @member {String} last_match_key
   */
  exports.prototype['last_match_key'] = undefined;



  return exports;
}));


