/**
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Webcast model module.
 * @module model/Webcast
 * @version 3.04.1
 */
class Webcast {
    /**
     * Constructs a new <code>Webcast</code>.
     * @alias module:model/Webcast
     * @param type {module:model/Webcast.TypeEnum} Type of webcast, typically descriptive of the streaming provider.
     * @param channel {String} Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe.
     */
    constructor(type, channel) { 
        
        Webcast.initialize(this, type, channel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, channel) { 
        obj['type'] = type;
        obj['channel'] = channel;
    }

    /**
     * Constructs a <code>Webcast</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Webcast} obj Optional instance to populate.
     * @return {module:model/Webcast} The populated <code>Webcast</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Webcast();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Type of webcast, typically descriptive of the streaming provider.
 * @member {module:model/Webcast.TypeEnum} type
 */
Webcast.prototype['type'] = undefined;

/**
 * Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe.
 * @member {String} channel
 */
Webcast.prototype['channel'] = undefined;

/**
 * File identification as may be required for some types. May be null.
 * @member {String} file
 */
Webcast.prototype['file'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Webcast['TypeEnum'] = {

    /**
     * value: "youtube"
     * @const
     */
    "youtube": "youtube",

    /**
     * value: "twitch"
     * @const
     */
    "twitch": "twitch",

    /**
     * value: "ustream"
     * @const
     */
    "ustream": "ustream",

    /**
     * value: "iframe"
     * @const
     */
    "iframe": "iframe",

    /**
     * value: "html5"
     * @const
     */
    "html5": "html5",

    /**
     * value: "rtmp"
     * @const
     */
    "rtmp": "rtmp",

    /**
     * value: "livestream"
     * @const
     */
    "livestream": "livestream"
};



export default Webcast;

